<a href="https://colab.research.google.com/github/Angelmaryann/Angelmaryann/blob/main/AngelaNumPyStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#ndarray.ndim
#Creating a 1-dimensional array
array_id = np.array([1,2,3])
array_id.ndim

1

In [ ]:
# Creating a 2-dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d.ndim

2

In [ ]:
#ndarray.shape
# Creating a 1-dimensional array
array_1d = np.array([1, 2, 3])
array_1d.shape

(3,)

In [ ]:
# Creating a 2-dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d.shape

(2, 3)

In [ ]:
#ndarray.size
# Creating a 1-dimensional array
array_1d = np.array([1, 2, 3])
array_1d.size

3

In [ ]:
# Creating a 2-dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d.size # Output: 6 - there are six elements in the 2D array

6

In [ ]:
#ndarray.dtype
# Creating an array of integers
int_array = np.array([1, 2, 3])
int_array.dtype # Output: int64 - data type is 64-bit integer

dtype('int64')

In [ ]:
# Creating an array of floating-point numbers
float_array = np.array([1.0, 2.5, 3.7])
float_array.dtype  # Output: float64 - data type is 64-bit floating-point number

dtype('float64')

In [ ]:
#ndarray.itemsize
int_array = np.array([1, 2, 3])
int_array.itemsize

8

In [ ]:
float_array = np.array([1.0, 2.5, 3.7])
float_array.itemsize

8

In [ ]:
#ndarray.data
# Creating an array of integers
int_array = np.array([1, 2, 3])
int_array.data

The output <memory at 0x...> is a representation of a memory address where the array's data is stored. It's important to note that accessing the data directly using the data attribute might not be necessary in typical use cases, as NumPy provides high-level operations that abstract away the need for direct memory manipulation.

However, understanding the data attribute can be relevant in certain situations where low-level memory access is required, such as interfacing with external libraries or optimizing performance-critical code.

If you need to access the data in a more user-friendly way, it's recommended to use indexing and slicing directly on the NumPy array, rather than using the data attribute. For example:

In [ ]:
# Accessing array elements using indexing
first_element = int_array[0]
first_element

1

In [ ]:
a1 = np.array([1, 2, 3, 4, 5, 6])
a1.shape

(6,)

In [ ]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a2.shape

(2, 4)

In [ ]:
a3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a3.shape

(3, 4)

In [ ]:
a4 = np.array([[[1,2,3],[4,5,6],[9,6,8]],[[4,8,9],[8,9,4],[8,5,4]]])
a4.shape

(2, 3, 3)

In [ ]:
a4[0, 1, 2]

6

In [ ]:
a4[:2]

array([[[1, 2, 3],
        [4, 5, 6],
        [9, 6, 8]],

       [[4, 8, 9],
        [8, 9, 4],
        [8, 5, 4]]])

In [ ]:
a4[:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [9, 6, 8]]])

In [ ]:
a2[1,2]

7

In [ ]:
a2[1:,:2]

array([[5, 6]])

In [ ]:
a1[:3]

array([1, 2, 3])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.empty(2)

array([1., 1.])

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
#np.linspace()
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 15, num=6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [ ]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [ ]:
#Sorting
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# ndarray.ndim, ndarray.size, ndarray.shape
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

Can you reshape an array?
This section covers arr.reshape()

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:


In [ ]:
y = np.arange(6)
y

array([0, 1, 2, 3, 4, 5])

You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

In [ ]:
c = y.reshape(3, 2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
d = y.reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

With np.reshape, you can specify a few optional parameters:

In [ ]:
np.reshape(y, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

a is the array to be reshaped.

newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

In many development environments as well as IPython and Jupyter Notebook, use the TAB button to get an overview of the available methods, for example air_quality.plot. + TAB.